### ISSUE TITLE
Replace Window option when Switching Projects

### ISSUE THREAD

**Issue by emmafaye** [agektmr/ProjectTabManager#29]
It would be cool if we could have a config option to always replace the current window with the new tabs when switching projects instead of opening a new window.

The easiest implementation, with the little knowledge of Chrome's API that I have would be to open a new window and then remove the last focused window. Something like this ```chrome.windows.remove(chrome.windows.getLastFocused)``` on this [line](https://github.com/agektmr/ProjectTabManager/blob/master/src/js/ProjectManager.js#L86).

This is probably a very crude solution however, but would love to see this feature so that I can keep my open windows to a minimum!

**Comment by agektmr** [comment]
@emmafaye On 4.0 you can click project name with shift key pressed to open the project and close current window at the same time. Hope this works for you.
