### ISSUE TITLE
Current window sometimes not displayed when clicking Prj Tab Mgr icon

### ISSUE THREAD

**Issue by WPWoodJr** [agektmr/ProjectTabManager#34]
I have had this issue where when I open a new window and then click on Project Tab Manager it only shows the bookmarked projects, not the current project '0'.

I did some digging and figured out that the window focus is changed and the winId is getting set to -1 (chrome.windows.WINDOW_ID_NONE) so I added this to the beginning of SessionManager.prototype.onfocuschanged and that fixed it:

			if (winId === chrome.windows.WINDOW_ID_NONE) { /// bug fix
				return;
			}

**Comment by WPWoodJr** [comment]
I think this may be fixed now?  I am not seeing it.

**Comment by agektmr** [comment]
This should be fixed. Closing the issue.
