### ISSUE TITLE
Better privacy when requesting favicons

### ISSUE THREAD

**Issue by makern** [agektmr/ProjectTabManager#40]
I would like to request that the FAVICON_URL be changed from `http://www.google.com/s2/favicons?domain=` to HTTPS.

Additionally it would be great to have an option to turn off favicon fetching entirely and always use the default icon. Or perhaps, fetch the icon from the actual site instead of Google.

It's a pretty big privacy issue to leak all the sites a user visits to Google. Especially since Google will automatically receive all their cookies on the google.com domain.

**Comment by agektmr** [comment]
This is implemented at 4.0. Thanks @makern for your report.

**Comment by makern** [comment]
Cheers! Can you clarify how this has been fixed? I can still see FAVICON_URL in the code but it doesn't appear to be used anymore?

**Comment by agektmr** [comment]
It's no longer used. Favicons are directly loaded from sources.
https://github.com/agektmr/ProjectTabManager/blob/master/src/elements/ptm-bookmark/ptm-bookmark.html#L202

**Comment by makern** [comment]
Great, thanks!
