### ISSUE TITLE
Add setting for treating every window as a project

### ISSUE THREAD

**Issue by kamykaze** [agektmr/ProjectTabManager#41]
I see the benefits of treating every window as a project, but I also find it very inconvenient to have to clean up my projects every day because I have too many projects I did not want.

It would be nice if we can turn this feature on/off in the options page.

Alternatively, I think a better approach might be to only treat new windows that have more than one tab as a project.

**Comment by dantman** [comment]
I too would prefer it if all windows were not automatically considered projects that stick around when the window is closed.

I'd like to be able to do some things related to one work project, name it and close the window, move on to another work project, name it and close, move on to a personal project, name it and close, and switch back to the first project; while also using chrome for various one-off web browsing tasks.

If I haven't given it a name, I have no need for it to stick around in the project list (in fact having to change the workflow, whether via trashing automatic "projects" or closing large windows in an awkward way will be tedious). Window/tab restore already covers the need to restore a recent or mistakenly closed window (and a session save/restoration tool is more reliable if I think I'll need to keep things around longer to restore mistakenly closed things). And a bunch of projects named with a cryptic datestamp doesn't help me find anything anyways.

I don't often open a single window with a single tab as a one-off. I normally open 2-3 tabs as a one-off (typically something distinct from what I'm currently doing, but in need of opening more than just a single tab) then close the window.

**Comment by agektmr** [comment]
I've added a new setting at 4.0 that limits number of anonymous sessions. For example, if you have 10 sessions that are not linked to any projects and the setting limits to 5, the 5 oldest sessions will be eliminated at the launch of extension. Defaults to unlimited. Hope this works for all of you. I'll close this issue for the moment. Let me know if you want better option.
