### ISSUE TITLE
Project bookmarking

### ISSUE THREAD

**Issue by WPWoodJr** [agektmr/ProjectTabManager#43]
I'd like to make a proposal for project bookmarking that might be more consistent, easier, and clearer to the user as to what is bookmarked and what isn't.  It would also remove empty projects that had had a bookmarked tab at one time.

1) Put a bookmark "star" icon on every project (next to the edit button) that indicates if the project has been bookmarked by whether the star is yellow or clear.

2) The user would be able to click the star in order to bookmark and un-bookmark all tabs in the project.  Un-bookmarking all tabs would not remove the session.

3) If the project is at first un-bookmarked and then becomes bookmarked by the user bookmarking one of the project's tabs then the star would turn yellow to indicate that at least one tab of the project has been bookmarked.  

4) If the user un-bookmarks every tab in the project individually then the star would be cleared and the project bookmark folder removed.  The session would remain.

5) If the user closes every tab (with CTRL^W) in an un-bookmarked project then the project session would go away, even if it was a "re-named" project.  

6) A re-named project would not be automatically bookmarked.  Only bookmarking a project tab or the whole project via the proposed star would create a bookmark.

7) Clicking the star off and then on again would bookmark all tabs, including any originally un-starred ones.

:-)

**Comment by WPWoodJr** [comment]
Also to consider as a possibility, but slightly more complex to manage auto-bookmarking of new tabs:
1) Have two shades of project yellow star, darker for a project bookmarked by clicking the project's star, lighter for a project bookmarked by bookmarking one or more tabs in the project.
2) If the user adds a tab to a project (window) with a darker star, the tab is automatically bookmarked
3) If the user adds a tab to a project with a lighter star, the tab is not automatically bookmarked
4) if the user clicks a project with a lighter star or a clear star, it becomes dark to indicate that every tab in the project is bookmarked
5) if the user clicks a project with a darker star, it becomes clear and all tab bookmarks removed and also the project bookmark folder; but the session remains

**Comment by WPWoodJr** [comment]
This approach would also resolve an issue I'm having when I rename a project.  Here's what happens:

1) Rename project on machine A but don't bookmark anything, just leave it for use on machine A as a session only

2) Machine B, C, etc get an empty project of that name

**Comment by agektmr** [comment]
Thanks @WPWoodJr for great suggestions!
There are 2 big issues that people ask me to fix.

1. piles of temporary sessions are annoying
2. what's been bookmarked is unclear

So I'm thinking of a new approach. Separate the window into 2 tabs: first is for sessions. second is for projects. You can link a session with one of projects.

I'm building this using Polymer now. Stay tuned.

**Comment by WPWoodJr** [comment]
>>>what's been bookmarked is unclear
That's why I suggested putting a star next to the project name to indicate if it was bookmarked or not.  

With two tabs, will projects also appear in the sessions tab?  I guess "open" projects would, right?  So maybe you can put a star to distinguish which are bookmarked :-)

**Comment by agektmr** [comment]
I hope 4.0 solved the issues. Closing for now.
