### ISSUE TITLE
Graphic glitch when opening the main menu

### ISSUE THREAD

**Issue by gonzaloserrano** [agektmr/ProjectTabManager#46]
Hi,

Sometimes when i click the icon i just get half of the window opened in OSX & Chrome 41.0.2272.104 (64-bit), like:

<img src="https://cloud.githubusercontent.com/assets/349328/7018517/c77bdbea-dd05-11e4-93c2-9d1b9099a58a.png" height="100">

Regards,

**Comment by agektmr** [comment]
Sorry for belated response. This issue is caused by browser itself rather than PTM. Similar things happens on other extensions as well.

**Comment by gonzaloserrano** [comment]
I'm using v4.0.0 and workes properly 👍
