### ISSUE TITLE
Wrong window detection

### ISSUE THREAD

**Issue by gonzaloserrano** [agektmr/ProjectTabManager#47]
Hi,

First, let me tell you that i love this extension, so thanks a lot. 

This is the first time i use it, and i have one issue: after managing my tabs manually i have 5 windows but Project Tab Manager just detects 4:

![projects](https://cloud.githubusercontent.com/assets/349328/7018559/4b00ecd0-dd06-11e4-818a-d0e8791c9597.png)

This is in OSX & Chrome 41.0.2272.104 (64-bit),

Regards,

**Comment by gonzaloserrano** [comment]
Ouch, later on when i create 2 new windows, the content of 2 of the 4 current ones have its contents changed for the 2 new ones :_(

**Comment by agektmr** [comment]
@gonzaloserrano Sorry for not paying much attention to your issue. If you still see the same problem on 4.0, please let me know.
