### ISSUE TITLE
Request: Auto-Bookmark

### ISSUE THREAD

**Issue by stefanfritsch** [agektmr/ProjectTabManager#55]
Hi,

I love your extension and use it extensively to archive and share tabs. But I often forget to bookmark a tab and only notice when I try to open it on another PC. Would it be possible to either 

* share the full window (including not-bookmarked tabs) or 
* to auto-bookmark tabs as they are created and delete them when they are closed?

The first solution is probably more elegant but the second might be easier to implement?

Ciao,
Stefan

**Comment by agektmr** [comment]
Thanks for using PTM!
One challenge here is that there's a quota on bookmarking via API. Changing bookmark too often causes unexpected breakage.
Alternative solution would be to use a separate cloud storage to sync tab status, but it costs too much comparing to the core concept of this extension.

I totally understand your expectation, but I can't implement the feature. Sorry about this :(

**Comment by agektmr** [comment]
Actually, Chrome has a convenient feature to open tabs active in other machines. See chrome://history/syncedTabs in your Chrome.

**Comment by stefanfritsch** [comment]
The Chrome solution unfortunately doesn't work if you need the tabs a week later. 

But thanks a lot for your explanation. I agree that it's probably too much effort for not enough benefit.

**Comment by peoro** [comment]
Hi, I love this extension. It does something I've been wishing for for a really long time. Thanks for creating it and making it open source. Great job for how it's written too: the code looks very clear, clean and elegant.

I also would love it if tabs were automatically bookmarked. At least the ones for one particular project window. All the time I'm using a project window forgetting to manually bookmark tabs and only find out about the oversight when I need those tabs. I think there might be some solutions, at least for my own use case. If we find a behavior that everyone likes I'd be happy to try and send a PR.

---

How does the quota work? According to [this old thread](https://groups.google.com/a/chromium.org/forum/#!msg/chromium-bugs/pumF2id8_bQ/aGAyDiOfkYAJ) it seems like exceeding the quota only affect the extension for one user for a few minutes. That doesn't seem too bad.

If that's the case:

1. We might run into the quota problem even with manual bookmarking. If I remember to save a project and frenetically star all its tabs at once, that's potentially worse than automatic bookmarking. The user should be notified of the issue in case of any error (that should be handled [around here](https://github.com/agektmr/ProjectTabManager/blob/e32821a36a0843fb4127cbf83e30b26eda5a04fb/src/elements/ptm-app/ptm-app.html#L405), right?).

2. There could be some generic workaround to the quota limits. For instance we could have a queue of tabs to bookmark which spaces every request by XX seconds.

I'd like it if the users could tick a per-project option to enable automatic bookmarking. A warning message could also let the user know about the possible quota issues...

**Comment by agektmr** [comment]
Hi @peoro thank for the feedback. Given HTML Import removal at Chrome 80, I'll have to work on a major rewrite of the extension. I might be able to add something if there's a chance, but no promise...
